population_events:
  - name: change_within_host_induced_recombination
    info:
      date: 2015/1/1
      value: false

  - name: change_mutation_probability_per_locus
    info:
      date: 2005/9/10
      mutation_probability_per_locus: 0.001

  - name: turn_off_mutation
    info:
      - date: 2002/1/1
      - date: 2012/1/1

  - name: turn_on_mutation
    info:
      - date: 2000/1/1
      - date: 2017/1/1

  - name: change_treatment_coverage
    info:
      - type: SteadyTCM
        date: 2007/2/1
        p_treatment_under_5_by_location: [ 0.600000 ]
        p_treatment_over_5_by_location: [ 0.550000 ]
#      - type: InflatedTCM
#        date: 2009/3/1
#        annual_inflation_rate: 0.01
#      - type: LinearTCM
#        from_date: 2007/6/1
#        to_date: 2008/12/1
#        p_treatment_under_5_by_location_to: [ 0.900000 ]
#        p_treatment_over_5_by_location_to: [ 0.90000 ]
#
  - name: change_treatment_strategy
    info:
      - date: 2007/3/2
        strategy_id: 0
      - date: 2017/6/2
        strategy_id: 3
      - date: 2027/9/2
        strategy_id: 4

  - name: single_round_MDA
    info:
      - date: 2020/1/1
        fraction_population_targeted: [ 1.0 ]
        days_to_complete_all_treatments: 14
      - date: 2020/2/8
        fraction_population_targeted: [ 0.03333333 ]
        days_to_complete_all_treatments: 14
      - date: 2020/3/14
        fraction_population_targeted: [ 0.7 ]
        days_to_complete_all_treatments: 14

  - name: modify_nested_mft_strategy
    info:
      - date: 2015/5/1
        strategy_id: 5
      - date: 2018/5/1
        strategy_id: 5

  - name: introduce_plas2_parasites
    info:
      - location: 0
        date: 2007/3/20
        fraction: 0.01
      - location: 1
        date: 2017/3/20
        fraction: 0.02

  - name: introduce_parasites
    info:
      - location: 0
        parasite_info:
          - date: 2007/3/20
            genotype_aa_sequence: "||||YY1||TTHFIMG,x||||||FNCMYRIPRPCA|1"
            number_of_cases: 5
          - date: 2007/4/15
            genotype_aa_sequence: '||||YY1||TTHFIMG,x||||||FNCMYRIPRPCA|1'
            number_of_cases: 5
      - location: 1
        parasite_info:
          - date: 2007/8/25
            genotype_aa_sequence: '||||YY1||TTHFIMG,x||||||FNCMYRIPRPCA|1'
            number_of_cases: 5
          - date: 2007/10/20
            genotype_aa_sequence: '||||YY1||TTHFIMG,x||||||FNCMYRIPRPCA|1'
            number_of_cases: 5

  - name: introduce_parasites_periodically
    info:
      - location: 0
        parasite_info:
          - duration: 10
            genotype_aa_sequence: '||||YY1||TTHFIMG,x||||||FNCMYRIPRPCA|1'
            number_of_cases: 1
            start_date: 2001/6/2
          - duration: 20
            genotype_aa_sequence: '||||YY1||TTHFIMG,x||||||FNCMYRIPRPCA|1'
            number_of_cases: 2
            start_date: 2011/6/2
      - location: 1
        parasite_info:
          - duration: 30
            genotype_aa_sequence: '||||YY1||TTHFIMG,x||||||FNCMYRIPRPCA|1'
            number_of_cases: 3
            start_date: 2003/6/2
          - duration: 40
            genotype_aa_sequence: '||||YY1||TTHFIMG,x||||||FNCMYRIPRPCA|1'
            number_of_cases: 4
            start_date: 2004/6/2

  - name: introduce_580Y_parasites
    info:
      - location: 2
        date: 2005/7/15
        fraction: 0.02
      - location: 22
        date: 2015/7/15
        fraction: 0.024

  - name: introduce_aq_mutant_parasites
    info:
      - location: 3
        date: 2007/4/30
        fraction: 0.05
      - location: 33
        date: 2017/4/30
        fraction: 0.055

  - name: introduce_lumefantrine_mutant_parasites
    info:
      - location: 4
        date: 2012/10/12
        fraction: 0.03
      - location: 5
        date: 2014/10/12
        fraction: 0.033

  - name: introduce_triple_mutant_to_dpm_parasites
    info:
      - location: 1
        date: 2013/12/20
        fraction: 0.04
      - location: 2
        date: 2014/12/20
        fraction: 0.05

  - name: change_interrupted_feeding_rate
    info:
      - location: 5
        date: 2001/6/1
        interrupted_feeding_rate: 0.5
      - location: 6
        date: 2002/8/15
        interrupted_feeding_rate: 0.7

 # TODO: change this event to match new genotype format
#  - name: introduce_parasites_periodically_v2
#    info:
#      - location: 0
#        parasite_info:
#          - duration: 10
#            number_of_cases: 1
#            start_date: 2008/2/1
#            end_date: 2008/2/1
#            allele_distributions:
#              - position: 0
#                distribution: [ 0.5, 0.5 ]
#              - position: 1
#                distribution: [ 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125 ]
#              - position: 2
#                distribution: [ 0.5, 0.5 ]
#              - position: 3
#                distribution: [ 0.5, 0.5 ]
#              - position: 4
#                distribution: [ 0.5, 0.5 ]


